ARM64: kernel: hwconf_manager: Fix strict-prototypes warning
../arch/arm64/kernel/hwconf_manager.c:205:26: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
  205 | static char *hw_item_dump()
      |                          ^
      |                           void
1 error generated.

Change-Id: I849936c32c0ead459c068f7048be1278c511424a
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>
(cherry picked from commit 17cf51ec88f0b297999ccf18f998bb496c9c15ba)
Signed-off-by: bcggxx <191667089+bcggxx@users.noreply.github.com>